version: "3.7"
  
services:
  sql-server-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "1qazXSW@"
        ACCEPT_EULA: "Y"
        MSSQL_COLLATION: "SQL_Latin1_General_CP1_CS_AS"
        MSSQL_PID: "Developer"
