name: .NET Core CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Start dependencies (docker-compose)
      run: docker-compose -f src/IssueTracker.DatabaseTesting/sql_server_start.yml up -d
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  

    - name: Restore dependencies
      run: dotnet restore src/IssueTrackerAPI

    - name: Build
      run: dotnet build src/IssueTrackerAPI --no-restore

    - name: Test
      run: dotnet test src/IssueTrackerAPI --no-build --verbosity normal

